services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: fruits_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: secure_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    environment:
      DB_HOST: mysql
      DB_NAME: fruits_db
      DB_USER: admin
      DB_PASS: secure_password
    depends_on:
      mysql:
        condition: service_healthy